# Generated by Django 4.2.3 on 2023-08-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
