# Generated by Django 4.2.3 on 2023-08-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMoney',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phno', models.CharField(blank=True, max_length=20, null=True)),
                ('card_no', models.CharField(blank=True, max_length=20, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=20, null=True)),
                ('selected_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('host_balance', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
