# Generated by Django 4.2.3 on 2023-08-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0005_addmoney_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTicket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('otp', models.CharField(blank=True, max_length=40, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('ticket_count', models.CharField(blank=True, max_length=100, null=True)),
                ('fare_amount', models.IntegerField(blank=True, null=True)),
                ('return_type', models.CharField(blank=True, max_length=10, null=True)),
                ('upi_pin', models.CharField(blank=True, max_length=200, null=True)),
                ('order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
