# Generated by Django 4.2.3 on 2023-08-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0008_login_otp_no_login_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
