# Generated by Django 4.2.3 on 2023-08-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0009_area'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='CityList',
        ),
    ]
