# Generated by Django 4.2.3 on 2023-08-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0012_remove_buyticket_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyticket',
            name='ticket_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
