# Generated by Django 4.2.3 on 2023-08-07 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0015_fareaount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmoney',
            old_name='phno',
            new_name='phone_no',
        ),
        migrations.RenameField(
            model_name='cardcreation',
            old_name='dataofbirth',
            new_name='data_of_birth',
        ),
        migrations.RenameField(
            model_name='cardcreation',
            old_name='phno',
            new_name='phone_no',
        ),
    ]
