# Generated by Django 4.2.3 on 2023-08-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0016_rename_phno_addmoney_phone_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardcreation',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
