# Generated by Django 4.2.3 on 2023-08-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0017_rename_data_of_birth_cardcreation_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
