# Generated by Django 4.2.3 on 2023-08-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0018_alter_login_password_alter_login_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='otp_no',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
