# Generated by Django 4.2.3 on 2023-08-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0019_alter_login_otp_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardcreation',
            name='otp_no',
        ),
    ]
